# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9961f2da75987ef2a81a8bf7d08c20f2bf9ec5edcbc52c2b0ef8266923b325d02b83bcf4bbe60ac4cba924210722e54894843bd4d1d177dd542d4e0feb2321d7

test:
  secret_key_base: 86e2675676172db0783f614c21eaf64fe259487dc82077e59f29dafe2cb9dace54f3d2492e88f84ca64c2916ff896314f5141d1518e94ef28f61fce191e19b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
